var trainData = {
    "validateMessagesShowId": "_validatorMessage",
    "status": true,
    "httpstatus": 200,
    "data": {
        "data": [{
            "start_station_name": "上海虹桥",
            "arrive_time": "----",
            "station_train_code": "D2287",
            "station_name": "上海虹桥",
            "train_class_name": "动车",
            "service_type": "2",
            "start_time": "07:47",
            "stopover_time": "----",
            "end_station_name": "深圳北",
            "station_no": "01",
            "isEnabled": true
        }, {
            "arrive_time": "08:11",
            "station_name": "嘉善南",
            "start_time": "08:28",
            "stopover_time": "17分钟",
            "station_no": "02",
            "isEnabled": true
        }, {
            "arrive_time": "08:37",
            "station_name": "嘉兴南",
            "start_time": "08:42",
            "stopover_time": "5分钟",
            "station_no": "03",
            "isEnabled": true
        }, {
            "arrive_time": "09:08",
            "station_name": "杭州东",
            "start_time": "09:10",
            "stopover_time": "2分钟",
            "station_no": "04",
            "isEnabled": true
        }, {
            "arrive_time": "09:29",
            "station_name": "绍兴北",
            "start_time": "09:31",
            "stopover_time": "2分钟",
            "station_no": "05",
            "isEnabled": true
        }, {
            "arrive_time": "09:50",
            "station_name": "余姚北",
            "start_time": "09:52",
            "stopover_time": "2分钟",
            "station_no": "06",
            "isEnabled": true
        }, {
            "arrive_time": "10:13",
            "station_name": "宁波",
            "start_time": "10:17",
            "stopover_time": "4分钟",
            "station_no": "07",
            "isEnabled": true
        }, {
            "arrive_time": "10:55",
            "station_name": "三门县",
            "start_time": "10:57",
            "stopover_time": "2分钟",
            "station_no": "08",
            "isEnabled": true
        }, {
            "arrive_time": "11:30",
            "station_name": "雁荡山",
            "start_time": "11:32",
            "stopover_time": "2分钟",
            "station_no": "09",
            "isEnabled": true
        }, {
            "arrive_time": "11:55",
            "station_name": "永嘉",
            "start_time": "11:57",
            "stopover_time": "2分钟",
            "station_no": "10",
            "isEnabled": true
        }, {
            "arrive_time": "12:08",
            "station_name": "温州南",
            "start_time": "12:10",
            "stopover_time": "2分钟",
            "station_no": "11",
            "isEnabled": true
        }, {
            "arrive_time": "12:28",
            "station_name": "鳌江",
            "start_time": "12:30",
            "stopover_time": "2分钟",
            "station_no": "12",
            "isEnabled": true
        }, {
            "arrive_time": "12:52",
            "station_name": "福鼎",
            "start_time": "12:54",
            "stopover_time": "2分钟",
            "station_no": "13",
            "isEnabled": true
        }, {
            "arrive_time": "13:24",
            "station_name": "福安",
            "start_time": "13:28",
            "stopover_time": "4分钟",
            "station_no": "14",
            "isEnabled": true
        }, {
            "arrive_time": "14:11",
            "station_name": "福州南",
            "start_time": "14:15",
            "stopover_time": "4分钟",
            "station_no": "15",
            "isEnabled": true
        }, {
            "arrive_time": "14:52",
            "station_name": "仙游",
            "start_time": "14:53",
            "stopover_time": "1分钟",
            "station_no": "16",
            "isEnabled": true
        }, {
            "arrive_time": "15:11",
            "station_name": "泉州",
            "start_time": "15:13",
            "stopover_time": "2分钟",
            "station_no": "17",
            "isEnabled": true
        }, {
            "arrive_time": "15:38",
            "station_name": "厦门北",
            "start_time": "15:42",
            "stopover_time": "4分钟",
            "station_no": "18",
            "isEnabled": true
        }, {
            "arrive_time": "16:01",
            "station_name": "漳州",
            "start_time": "16:05",
            "stopover_time": "4分钟",
            "station_no": "19",
            "isEnabled": true
        }, {
            "arrive_time": "17:02",
            "station_name": "潮汕",
            "start_time": "17:05",
            "stopover_time": "3分钟",
            "station_no": "20",
            "isEnabled": true
        }, {
            "arrive_time": "17:31",
            "station_name": "普宁",
            "start_time": "17:33",
            "stopover_time": "2分钟",
            "station_no": "21",
            "isEnabled": true
        }, {
            "arrive_time": "17:48",
            "station_name": "葵潭",
            "start_time": "17:50",
            "stopover_time": "2分钟",
            "station_no": "22",
            "isEnabled": true
        }, {
            "arrive_time": "18:25",
            "station_name": "鲘门",
            "start_time": "18:27",
            "stopover_time": "2分钟",
            "station_no": "23",
            "isEnabled": true
        }, {
            "arrive_time": "18:52",
            "station_name": "惠州南",
            "start_time": "18:54",
            "stopover_time": "2分钟",
            "station_no": "24",
            "isEnabled": true
        }, {
            "arrive_time": "19:25",
            "station_name": "深圳北",
            "start_time": "19:25",
            "stopover_time": "----",
            "station_no": "25",
            "isEnabled": true
        }]
    },
    "messages": [],
    "validateMessages": {}
};

trainData.data.data.forEach((ele, index) => {
	console.log(JSON.stringify(ele));
});
